[package]
name = "derive"
version = "0.1.0"
authors = ["Sean Smith <scsmithr@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
ebnf = { path = "../ebnf" }
quote = "1.0"
syn = "1.0"
proc-macro2 = "1.0"
