[package]
name = "smol"
version = "0.1.0"
authors = ["Sean Smith <scsmithr@gmail.com>"]
edition = "2018"

[dependencies]
ebnf = { path = "../ebnf" }
derive = { path = "../derive" }
parsegen = { path = "../parsegen" }
anyhow = "1.0"
